---
# This playbook composes OSTree
- name: Create directory structure
  file: path={{ item }} state=directory mode=750
  with_items:
  - "/srv/repo"
  - "/srv/cache"
  - "/workspace"

- name: Initialize OSTree repository
  command:
    ostree --repo=/srv/repo init --mode=archive

- name: Clone Fedora-Atomic buildscripts
  git:
    repo=https://pagure.io/fedora-atomic.git
    version=f25
    depth=1
    dest=/workspace/fedora-atomic

- name: Compose Fedora-Atomic Tree
  command:
    chdir=/workspace/fedora-atomic
    rpm-ostree compose tree --cachedir=/srv/cache --repo=/srv/repo ./fedora-atomic-docker-host.json

- name: Running Http server at Port 35000, Use `ip addr` to check the IP Address...
  shell:
    /usr/local/bin/daemon -- ostree trivial-httpd -P 35000 --log-file - /srv
