---
# This playbook installs requirements
- name: Install the list of required packages
  package: name={{ item }} state=installed
  with_items:
  - genisoimage
  - libvirt
  - libselinux-python
  - qemu-img
  - rpm-ostree
  - ostree
  - virt-install

- name: Download daemon rpm and Install
  command: "{{ item }}"
  with_items:
    - wget -P /tmp http://libslack.org/daemon/download/daemon-0.6.4-1.x86_64.rpm
    - rpm --install /tmp/daemon-0.6.4-1.x86_64.rpm
  ignore_errors: yes
